### ISSUE TITLE
Enumerator failed to MoveNextAsync

### ISSUE THREAD

**Issue by saidsalti** [JasonGT/CleanArchitecture#24]
Hello ..
I have a problem.
When I perform any operation(Update,Insert ,Read), this error is shown (Enumerator failed to MoveNextAsync).
I did not understand what it means.
I could not add any record to the database.

Thank you.

**Comment by khaledafify** [comment]
did you solve this issue ?

**Comment by litan1106** [comment]
I ran into the same issue.

**Comment by alcidesfmelof** [comment]
Having this problem now? Any update?
@saidsalti

**Comment by iayti** [comment]
I'm not sure as I can't see the exact details of the error, but I encountered this error when I used an inactive token. For example, you add a user to db and create a valid token. After that if you delete the user, The error will be occur. Because of the below code: user is null and Behaviours cannot work properly

https://github.com/jasontaylordev/CleanArchitecture/blob/master/src/Infrastructure/Identity/IdentityService.cs

```csharp
public async Task<string> GetUserNameAsync(string userId)
{
            var user = await _userManager.Users.FirstAsync(u => u.Id == userId);

            //TODO: If user is null. Response will be user not found.

            return user.UserName;
}
```
