### ISSUE TITLE
[Question] Why do you create the handler inside of the command itself?

### ISSUE THREAD

**Issue by davidhenley** [JasonGT/CleanArchitecture#25]

**Comment by hypervtechnics** [comment]
I think this is to save some "file count", as most of the commands are empty. You can split them in two separate code files and classes if you want to.

**Comment by davidhenley** [comment]
I usually set up mine like:

```
public class AddTodo
{
    public class Command : IRequest
    {
    }

    public class Validator : AbstractValidator<Command>
    {
    }

    public class Handler : IRequestHandler<Command, Unit>
    {
    }
}
```

Just wanted to understand the thinking behind this way since I've never seen it before.

**Comment by JasonGT** [comment]
It improves discoverability of the request handlers via the requests. For example, within an ASP.NET Controller I might have:

```
_mediator.Send(new AddTodoCommand { ... });
```

If I press F12 I can review the request and request handler at the same time. I don't have to use solution explorer or keyboard wizardry to load the handler. It's all there ready to review and edit.

Going forward, I was planning to change to this approach:

**AddTodoCommand.cs**
```
public class AddTodoCommand 
{
}

public class AddTodoCommandHandler
{
}
```

Since the way that I have nested makes it a bit hard to understand.

But I like your approach too, the request, validator, handler ordering is great. Very clean - I'll give it a try.

Thanks for sharing. 👍

**Comment by morgrowe** [comment]
@JasonGT Just a minor thing I stumbled on today in relation to this question.

Visual Studio CA tools complains about nesting public classes inside of other public classes: [CA1034](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1034?view=vs-2019).

I see in your final comment, you mentioned you were planning on using this approach:

```
public class AddTodoCommand 
{
}

public class AddTodoCommandHandler
{
}
```

Is that still the approach you'd recommend? Or do you think something like:

```
public class AddTodoCommand 
{
    private class AddTodoCommandHandler
    {
    }
}
```

Is cleaner?

Cheers,
Morgan

**Comment by alberthoekstra** [comment]
I like the approach of @davidhenley too, it's way faster to create new commands like this. Just rename 1 single class and your good to go.

But currently I'm not using it because I use Nswag to generate Typscript classes. If I use this 1 file approach I get lots of typscript classes with same 'Request, command, etc.' names.

**Comment by davidhenley** [comment]
@alberthoekstra you can change the config to use the DeclaringType name so you have the right client names.

**Comment by alberthoekstra** [comment]
@davidhenley happen to have an example of that? I can't figure it out unfortunately, I don't have much experience with nswag.
